'use client';

import Link from 'next/link';
import { AnimatePresence, motion } from 'framer-motion';
import {
  ArrowRight,
  Award,
  BarChart3,
  BookOpen,
  CalendarDays,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  Clock3,
  Code2,
  ExternalLink,
  Facebook,
  Github,
  Globe2,
  Linkedin,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Phone,
  Play,
  Search,
  ShieldCheck,
  Sparkles,
  Star,
  Users,
  X,
  Youtube,
} from 'lucide-react';
import { FormEvent, useEffect, useState } from 'react';
import { courses, features, navItems, projects, testimonials, type Course } from '@/lib/tevexxo-data';

const reveal = { hidden: { opacity: 0, y: 18 }, visible: { opacity: 1, y: 0 } };
const sectionMotion = { initial: 'hidden', whileInView: 'visible', viewport: { once: true, amount: 0.12 }, transition: { staggerChildren: 0.08 } };

function Brand({ light = false }: { light?: boolean }) {
  return <Link href="/" className={`flex items-center gap-2 text-xl font-black tracking-tight ${light ? 'text-white' : 'text-slate-950'}`} aria-label="Tevexxo home"><span className="brand-mark"><span /><span /><span /></span><span>Tevexxo</span></Link>;
}

function SearchOverlay({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [query, setQuery] = useState('');
  const results = [...courses.map((item) => ({ title: item.title, type: 'Course' })), ...projects.map((item) => ({ title: item.title, type: 'Project' }))].filter((item) => item.title.toLowerCase().includes(query.toLowerCase()));
  useEffect(() => { const handleKey = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; window.addEventListener('keydown', handleKey); return () => window.removeEventListener('keydown', handleKey); }, [onClose]);
  return <AnimatePresence>{open && <motion.div className="fixed inset-0 z-50 bg-slate-950/70 p-4 backdrop-blur-md" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose}><motion.div className="mx-auto mt-20 max-w-2xl overflow-hidden rounded-3xl bg-white shadow-2xl" initial={{ y: -20, scale: .98 }} animate={{ y: 0, scale: 1 }} exit={{ y: -20, scale: .98 }} onClick={(event) => event.stopPropagation()}><div className="flex items-center gap-3 border-b border-slate-200 p-5"><Search size={20} className="text-orange-500" /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search courses and projects" className="flex-1 bg-transparent text-lg outline-none" /><button onClick={onClose} aria-label="Close search"><X size={20} /></button></div><div className="max-h-80 overflow-auto p-3">{results.length ? results.map((item) => <Link key={item.title} href={item.type === 'Course' ? '/courses' : '/projects'} onClick={onClose} className="flex items-center justify-between rounded-xl px-4 py-3 hover:bg-orange-50"><span className="font-semibold text-slate-900">{item.title}</span><span className="text-xs font-bold uppercase tracking-wider text-slate-400">{item.type}</span></Link>) : <p className="p-6 text-center text-slate-500">No matching learning paths yet.</p>}</div></motion.div></motion.div>}</AnimatePresence>;
}

function DemoModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [sent, setSent] = useState(false);
  const [error, setError] = useState('');
  const handleSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (!form.get('name') || !form.get('email') || !form.get('course')) { setError('Please fill in your name, email and course.'); return; } setError(''); setSent(true); };
  return <AnimatePresence>{open && <motion.div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 p-4 backdrop-blur-md" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose}><motion.div className="w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl sm:p-8" initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 18 }} onClick={(event) => event.stopPropagation()}>{sent ? <div className="py-12 text-center"><div className="mx-auto mb-5 flex h-16 w-16 items-center justify-center rounded-full bg-emerald-100 text-emerald-600"><Check size={30} /></div><h2 className="text-2xl font-black text-slate-950">You’re on the list.</h2><p className="mt-2 text-slate-500">Our learning advisor will reach out to arrange your free demo.</p><button onClick={onClose} className="mt-7 rounded-full bg-slate-950 px-6 py-3 text-sm font-bold text-white">Close</button></div> : <><div className="mb-6 flex items-start justify-between"><div><p className="eyebrow">FREE DEMO</p><h2 className="mt-2 text-2xl font-black text-slate-950">See what learning with Tevexxo feels like.</h2></div><button onClick={onClose} aria-label="Close demo"><X /></button></div><form onSubmit={handleSubmit} className="grid gap-4 sm:grid-cols-2"><label className="field">Name<input name="name" placeholder="Your full name" /></label><label className="field">Email<input name="email" type="email" placeholder="you@example.com" /></label><label className="field">Phone<input name="phone" placeholder="+91 98765 43210" /></label><label className="field">Interested course<select name="course" defaultValue=""><option value="" disabled>Choose a path</option>{courses.map((course) => <option key={course.title}>{course.title}</option>)}</select></label><label className="field sm:col-span-2">Preferred date<input name="date" type="date" /></label><label className="field sm:col-span-2">Message<textarea name="message" rows={3} placeholder="Tell us what you want to learn" /></label>{error && <p className="sm:col-span-2 text-sm font-semibold text-red-600">{error}</p>}<div className="flex justify-end gap-3 sm:col-span-2"><button type="button" onClick={onClose} className="rounded-full border border-slate-200 px-5 py-3 text-sm font-bold text-slate-600">Cancel</button><button className="rounded-full bg-orange-500 px-6 py-3 text-sm font-bold text-white shadow-lg shadow-orange-500/20">Submit request <ArrowRight size={16} className="ml-1 inline" /></button></div></form></>}</motion.div></motion.div>}</AnimatePresence>;
}

function Navbar({ onSearch, onDemo }: { onSearch: () => void; onDemo: () => void }) {
  const [menuOpen, setMenuOpen] = useState(false);
  return <header className="absolute inset-x-0 top-0 z-40"><div className="container flex h-20 items-center justify-between"><Brand light /><nav className="hidden items-center gap-6 lg:flex">{navItems.map((item, index) => <Link key={item.label} href={item.href} className={`nav-link ${index === 0 ? 'active' : ''}`}>{item.label}{['Courses', 'Programs'].includes(item.label) && <span className="ml-1 text-[9px]">⌄</span>}</Link>)}</nav><div className="hidden items-center gap-3 sm:flex"><button onClick={onSearch} className="icon-button" aria-label="Search"><Search size={18} /></button><button onClick={onDemo} className="orange-button">Get Started <ArrowRight size={16} /></button></div><button className="text-white lg:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X /> : <Menu />}</button></div><AnimatePresence>{menuOpen && <motion.nav className="mx-4 rounded-2xl border border-white/10 bg-slate-950/95 p-3 shadow-2xl lg:hidden" initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}>{navItems.map((item) => <Link key={item.label} href={item.href} onClick={() => setMenuOpen(false)} className="block rounded-xl px-4 py-3 text-sm font-semibold text-white hover:bg-white/10">{item.label}</Link>)}<button onClick={onDemo} className="mt-2 w-full rounded-xl bg-orange-500 px-4 py-3 text-sm font-bold text-white">Get Started <ArrowRight size={15} className="ml-1 inline" /></button></motion.nav>}</AnimatePresence></header>;
}

function Hero({ onDemo }: { onDemo: () => void }) {
  const orbitCards = [{ label: 'AI & Machine\nLearning', icon: '✦', className: 'left-0 top-3' }, { label: 'Cyber\nSecurity', icon: '◇', className: 'right-0 top-9' }, { label: 'Full Stack\nDevelopment', icon: '</>', className: 'left-8 top-28' }, { label: 'Cloud &\nDevOps', icon: '☁', className: 'right-0 top-32' }, { label: 'Data\nAnalytics', icon: '▥', className: 'left-12 bottom-16' }, { label: 'UI/UX\nDesign', icon: '⌘', className: 'right-12 bottom-9' }];
  return <section id="home" className="hero-grid relative overflow-hidden"><div className="container relative z-10 grid min-h-[650px] items-center gap-10 pb-28 pt-28 lg:grid-cols-[.95fr_1.05fr] lg:pb-32 lg:pt-24"><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6 }}><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.06] px-4 py-2 text-[11px] font-semibold text-slate-200">Empowering Future Tech Leaders <span className="text-orange-400">✦</span></div><h1 className="max-w-xl text-5xl font-black leading-[.98] tracking-[-.04em] text-white sm:text-6xl">Build Skills.<br />Build Your <span className="text-orange-500">Future.</span></h1><p className="mt-6 max-w-lg text-base leading-7 text-slate-300">Industry-focused training programs to help you learn, build real-world projects and become career-ready.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="#courses" className="orange-button">Explore Courses <ArrowRight size={17} /></Link><button onClick={onDemo} className="outline-button">Book Free Demo <CalendarDays size={16} /></button></div><div className="mt-9 flex items-center gap-4"><div className="flex -space-x-3">{['PS', 'AK', 'NP', 'RV'].map((avatar) => <span key={avatar} className="avatar-ring">{avatar}</span>)}</div><div><p className="text-sm font-bold text-white">10K+ Learners</p><p className="text-xs text-slate-400">already growing with us</p></div></div></motion.div><div className="relative mx-auto h-[380px] w-full max-w-[580px] sm:h-[440px]"><div className="absolute left-1/2 top-1/2 h-56 w-56 -translate-x-1/2 -translate-y-1/2 rounded-full bg-orange-500/20 blur-3xl" /><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="orbit orbit-three" /><motion.div className="hero-emblem" animate={{ y: [0, -8, 0], rotate: [0, 2, 0] }} transition={{ duration: 5, repeat: Infinity, ease: 'easeInOut' }}><div className="brand-mark large"><span /><span /><span /></div></motion.div>{orbitCards.map((card, index) => <motion.div key={card.label} className={`tech-float ${card.className}`} initial={{ opacity: 0, scale: .85 }} animate={{ opacity: 1, scale: 1, y: [0, index % 2 ? -5 : 5, 0] }} transition={{ delay: .3 + index * .08, duration: 4 + index * .2, repeat: Infinity, repeatType: 'reverse' }}><span className="text-orange-400">{card.icon}</span><span>{card.label.split('\n').map((line) => <span key={line} className="block">{line}</span>)}</span></motion.div>)}</div></div><div className="wave-bottom" /></section>;
}

function Stats() {
  const stats: { value: string; label: string; icon: typeof Users }[] = [
    { value: '10K+', label: 'Active Learners', icon: Users },
    { value: '25+', label: 'Industry Programs', icon: BookOpen },
    { value: '95%', label: 'Completion Rate', icon: Award },
    { value: '50+', label: 'Expert Mentors', icon: Users },
  ];
  return (
    <div className="container relative z-20 -mt-10">
      <div className="grid overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-[0_18px_50px_rgba(15,23,42,.1)] sm:grid-cols-2 lg:grid-cols-4">
        {stats.map((stat, index) => {
          const StatIcon = stat.icon;
          return (
            <div key={stat.label} className={`flex items-center gap-4 px-6 py-6 ${index ? 'border-t border-slate-100 sm:border-l lg:border-t-0' : ''}`}>
              <div className="stat-icon"><StatIcon size={21} /></div>
              <div>
                <p className="text-2xl font-black text-slate-950">{stat.value}</p>
                <p className="text-xs font-medium text-slate-500">{stat.label}</p>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function SectionHeading({ eyebrow, title, accent, action }: { eyebrow: string; title: string; accent: string; action?: React.ReactNode }) { return <div className="mb-8 flex items-end justify-between gap-4"><div><p className="eyebrow">{eyebrow}</p><h2 className="mt-2 text-3xl font-black tracking-tight text-slate-950 sm:text-4xl">{title} <span className="text-orange-500">{accent}</span></h2></div>{action}</div>; }

function CourseCard({ course }: { course: Course }) { const Icon = course.icon; return <motion.article variants={reveal} whileHover={{ y: -6 }} className={`relative flex min-h-[330px] flex-col rounded-2xl border bg-white p-5 shadow-sm transition-shadow hover:shadow-xl ${course.featured ? 'border-orange-400 shadow-orange-100' : 'border-slate-100'}`}>{course.featured && <span className="absolute right-4 top-4 rounded-full bg-orange-500 px-3 py-1 text-[9px] font-black tracking-wider text-white">POPULAR</span>}<div className={`mb-5 flex h-12 w-12 items-center justify-center rounded-xl text-white shadow-lg ${course.iconClass}`}><Icon size={24} /></div><h3 className="max-w-[180px] text-lg font-black leading-tight text-slate-950">{course.title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{course.description}</p><div className="mt-4 flex flex-wrap gap-1.5">{course.technologies.map((tech) => <span key={tech} className="rounded bg-slate-100 px-2 py-1 text-[9px] font-semibold text-slate-600">{tech}</span>)}</div><div className="mt-auto flex items-center gap-2 border-t border-slate-100 pt-4 text-[10px] text-slate-500"><Clock3 size={13} />{course.duration}<span className="mx-1 text-slate-300">•</span>{course.level}</div><div className="mt-3 flex items-center justify-between"><span className="flex items-center gap-1 text-xs font-bold text-orange-500"><Star size={13} fill="currentColor" /> {course.rating} <span className="font-normal text-slate-400">({course.reviews})</span></span><Link href="/courses" className={`flex h-8 w-8 items-center justify-center rounded-full border ${course.featured ? 'border-orange-500 bg-orange-500 text-white' : 'border-slate-200 text-slate-600'}`} aria-label={`Explore ${course.title}`}><ArrowRight size={15} /></Link></div></motion.article>; }

function Courses() { return <section id="courses" className="section-space bg-slate-50"><div className="container"><SectionHeading eyebrow="OUR COURSES" title="Explore Our" accent="Top Courses" action={<Link href="/courses" className="hidden items-center gap-2 text-xs font-bold text-slate-600 sm:flex">View All Courses <ArrowRight size={14} /></Link>} /><motion.div {...sectionMotion} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{courses.map((course) => <CourseCard course={course} key={course.title} />)}</motion.div><Link href="/courses" className="mt-6 flex items-center justify-center gap-2 text-xs font-bold text-orange-500 sm:hidden">View All Courses <ArrowRight size={14} /></Link></div></section>; }

function Projects() { return <section id="projects" className="section-space bg-white"><div className="container"><SectionHeading eyebrow="REAL WORLD PROJECTS" title="Build. Showcase." accent="Get Hired." action={<Link href="/projects" className="hidden items-center gap-2 text-xs font-bold text-slate-600 sm:flex">View All Projects <ArrowRight size={14} /></Link>} /><motion.div {...sectionMotion} className="grid gap-5 lg:grid-cols-3">{projects.map((project, index) => <motion.article variants={reveal} whileHover={{ y: -6 }} key={project.title} className={`overflow-hidden rounded-2xl border bg-white shadow-sm ${index === 1 ? 'border-orange-400 shadow-orange-100' : 'border-slate-100'}`}><div className={`relative flex h-44 items-center justify-center overflow-hidden bg-gradient-to-br ${project.color}`}><div className="absolute inset-0 tech-lines opacity-30" /><div className="relative w-4/5 rounded-xl border border-white/20 bg-slate-950/70 p-3 shadow-2xl"><div className="mb-3 flex gap-1"><span className="h-1.5 w-1.5 rounded-full bg-red-400" /><span className="h-1.5 w-1.5 rounded-full bg-yellow-400" /><span className="h-1.5 w-1.5 rounded-full bg-green-400" /></div><div className="grid grid-cols-[.8fr_1.2fr] gap-2"><div className="h-20 rounded bg-white/10" /><div className="space-y-2"><div className="h-3 w-2/3 rounded bg-orange-400/70" /><div className="h-10 rounded bg-white/10" /><div className="flex gap-2"><div className="h-2 w-1/3 rounded bg-white/30" /><div className="h-2 w-1/4 rounded bg-white/20" /></div></div></div></div><span className="absolute left-4 top-4 rounded bg-orange-500 px-2 py-1 text-[9px] font-black text-white">FEATURED</span></div><div className="p-5"><h3 className="text-lg font-black text-slate-950">{project.title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{project.description}</p><div className="mt-4 flex flex-wrap gap-1.5">{project.technologies.map((tech) => <span key={tech} className="rounded bg-orange-50 px-2 py-1 text-[9px] font-semibold text-orange-600">{tech}</span>)}</div><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4 text-[10px] font-semibold text-slate-600"><span><ExternalLink size={13} className="mr-1 inline" />Live Demo</span><span><Github size={13} className="mr-1 inline" />Source Code</span><span className="text-orange-500">{project.views}<br /><small className="font-normal text-slate-400">Views</small></span></div></div></motion.article>)}</motion.div></div></section>; }

function WhyTevexxo() { return <section id="why-tevexxo" className="bg-slate-50 py-14"><div className="container"><SectionHeading eyebrow="WHY CHOOSE TEVEXXO?" title="Learn with a" accent="real advantage." /><motion.div {...sectionMotion} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{features.map((feature) => { const Icon = feature.icon; return <motion.div variants={reveal} whileHover={{ y: -3 }} key={feature.title} className="flex gap-4 rounded-2xl border border-slate-100 bg-white p-5"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-orange-50 text-orange-500"><Icon size={20} /></div><div><h3 className="text-sm font-black text-slate-950">{feature.title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{feature.description}</p></div></motion.div>; })}</motion.div></div></section>; }

function Testimonials() { const [active, setActive] = useState(0); const visible = testimonials.slice(active, active + 3); return <section className="bg-white py-14"><div className="container"><SectionHeading eyebrow="WHAT OUR LEARNERS SAY" title="Real stories from" accent="real learners." action={<div className="flex gap-2"><button onClick={() => setActive(Math.max(0, active - 1))} className="carousel-button" aria-label="Previous testimonial"><ChevronLeft size={16} /></button><button onClick={() => setActive(Math.min(testimonials.length - 3, active + 1))} className="carousel-button" aria-label="Next testimonial"><ChevronRight size={16} /></button></div>} /><motion.div layout className="grid gap-4 md:grid-cols-3">{visible.map((testimonial) => <motion.article layout key={testimonial.name} className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><div className="mb-4 text-3xl font-black leading-none text-orange-500">“</div><p className="min-h-[60px] text-xs leading-5 text-slate-600">{testimonial.quote}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><div className="flex items-center gap-3"><span className="avatar-ring small">{testimonial.avatar}</span><div><p className="text-xs font-black text-slate-950">{testimonial.name}</p><p className="text-[10px] text-slate-400">{testimonial.role}</p></div></div><div className="flex text-orange-500">{[1, 2, 3, 4, 5].map((star) => <Star key={star} size={12} fill="currentColor" />)}</div></div></motion.article>)}</motion.div></div></section>; }

function CTA() { const [email, setEmail] = useState(''); const [status, setStatus] = useState(''); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!email || !/\S+@\S+\.\S+/.test(email)) { setStatus('Please enter a valid email.'); return; } setStatus('You’re in. Check your inbox for the next step.'); setEmail(''); }; return <section id="programs" className="bg-white px-4 pb-16"><div className="container"><div className="cta-panel relative overflow-hidden rounded-[26px] px-6 py-8 sm:px-12 sm:py-10"><div className="relative z-10 flex flex-col items-start gap-6 lg:flex-row lg:items-center lg:justify-between"><div><div className="mb-3 flex items-center gap-3"><span className="brand-mark"><span /><span /><span /></span><span className="text-sm font-bold text-orange-500">TEVEXXO</span></div><h2 className="text-2xl font-black text-white sm:text-3xl">Ready to Upgrade Your Tech Skills?</h2><p className="mt-2 text-sm text-slate-400">Join thousands of learners and start your journey with Tevexxo today.</p></div><form onSubmit={submit} className="w-full max-w-md"><div className="flex rounded-xl border border-white/15 bg-white/5 p-1"><input value={email} onChange={(event) => setEmail(event.target.value)} type="email" placeholder="Enter your email address" className="min-w-0 flex-1 bg-transparent px-3 text-sm text-white outline-none placeholder:text-slate-500" aria-label="Email address" /><button className="shrink-0 rounded-lg bg-orange-500 px-4 py-3 text-xs font-black text-white shadow-lg shadow-orange-500/20">Start Learning <ArrowRight size={14} className="ml-1 inline" /></button></div>{status && <p className={`mt-2 text-xs ${status.startsWith('Please') ? 'text-red-300' : 'text-emerald-300'}`}>{status}</p>}</form></div></div></div></section>; }

function Footer() { return <footer className="bg-slate-950 text-slate-400"><div className="container grid gap-10 py-14 sm:grid-cols-2 lg:grid-cols-[1.5fr_repeat(4,1fr)]"><div><Brand light /><p className="mt-5 max-w-xs text-xs leading-5">Empowering future tech leaders with industry-relevant training and real-world learning experiences.</p><div className="mt-5 flex gap-2">{[Facebook, Youtube, Linkedin, Github].map((Icon) => <a key={Icon.displayName} href="#" className="social-button" aria-label="Social link"><Icon size={14} /></a>)}</div></div>{[['COURSES', ['Full Stack Development', 'AI & Machine Learning', 'Data Analytics', 'Cyber Security', 'Cloud & DevOps', 'UI/UX Design']], ['PROGRAMS', ['Certification Programs', 'Industry Projects', 'Internships', 'Workshops', 'Career Support']], ['COMPANY', ['About Us', 'Our Mentors', 'Blog', 'Careers', 'Contact Us']], ['SUPPORT', ['Help Center', 'FAQ', 'Privacy Policy', 'Terms & Conditions']]].map(([title, links]) => <div key={String(title)}><p className="footer-title">{title}</p><ul className="mt-4 space-y-2 text-xs">{(links as string[]).map((link) => <li key={link}><a href="#" className="hover:text-orange-400">{link}</a></li>)}</ul></div>)}<div className="sm:col-span-2 lg:col-span-1"><p className="footer-title">CONTACT US</p><ul className="mt-4 space-y-3 text-xs"><li><Mail size={14} className="mr-2 inline text-orange-500" />hello@tevexxo.com</li><li><Phone size={14} className="mr-2 inline text-orange-500" />+91 98765 43210</li><li><MapPin size={14} className="mr-2 inline text-orange-500" />Bangalore, India</li></ul></div></div><div className="container border-t border-white/10 py-5 text-center text-[11px]">© 2024 Tevexxo. All Rights Reserved.</div></footer>; }

export default function TevexxoPage() { const [searchOpen, setSearchOpen] = useState(false); const [demoOpen, setDemoOpen] = useState(false); return <div className="min-h-screen bg-slate-50"><Navbar onSearch={() => setSearchOpen(true)} onDemo={() => setDemoOpen(true)} /><Hero onDemo={() => setDemoOpen(true)} /><Stats /><main><Courses /><Projects /><WhyTevexxo /><Testimonials /><CTA /></main><Footer /><SearchOverlay open={searchOpen} onClose={() => setSearchOpen(false)} /><DemoModal open={demoOpen} onClose={() => setDemoOpen(false)} /></div>; }
